seva/seva/urls.py
from django.contrib import admin
from django.urls import path


from .views import home, login_user, logout_user, clock_in_report, attend_report

urlpatterns = [
    path('', home),
    path('login/', login_user),
    path('logout/', logout_user),
    path('admin/', admin.site.urls),
    path('clock-in-report', clock_in_report),
    path('attend-report', attend_report)
]

seva/persons/models.py
from django.db import models

class Person(models.Model):
    GENDER = [
        ("M", "MALE"),
        ("F", "FEMALE"),
    ]
    badge = models.CharField(max_length=6)
    full_name = models.CharField(max_length=25, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER)
    contact_number = models.CharField(max_length=10)
    active = models.BooleanField(default=True)

    type = models.ForeignKey('auth.Group', on_delete=models.CASCADE)
    centre = models.ForeignKey("centres.Centre", on_delete=models.CASCADE, null=True)
    department = models.ForeignKey("departments.Department", on_delete=models.CASCADE, null=True)

    centre_badge = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.badge

    def save(self, *args, **kwargs):
        # auto create badge for visitor or guest
        if self.type.name == "VISITOR":
            badge = 'V' + format(int(len(Person.objects.filter(type__name="VISITOR")) + 1), '05d')
            self.badge = badge
        if self.type.name == "GUEST":
            badge = 'G' + format(int(len(Person.objects.filter(type__name="GUEST")) + 1), '05d')
            self.badge = badge
        self.centre_badge = self.centre.code + self.badge

        for field_name in ['badge', 'full_name']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.upper())

        super(Person, self).save(*args, **kwargs)

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title> SEVA </title>  
        <style>
            /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
            /* ~~~~~~~~~~~ ALL */
            html {
                height: 100%;
            }
            body {  
                font-family: Calibri, Helvetica, sans-serif;  
                background-color: rgb(200, 200, 200);
                <!-- height: 90%; -->
            }
            button, input, select{
                background-color: rgb(240, 240, 240);
                padding: 0.5rem;
                border: none;
                margin: 0.2rem;
            }
            form {
                max-width: 1000px
            }

            /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
            /* ~~~~~~~~~~~ LOGIN */
            .login {
                width: 100%;
            }
            .login h1 {
                /* background-color: rgb(70, 70, 70); */
                padding: 1rem;
            }
            .login input[type=text], .login input[type=password] {
                display: inline-block;
                padding: 0.5rem;
                /* color: rgb(255, 255, 255); */
                /* background-color: rgb(50, 50, 50); */
            }

            /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
            /* ~~~~~~~~~~~ LOGOUT */
            .logout {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                min-width: 1050px;
                background-color: rgb(248, 248, 248);
                /* color: white; */
            }
            .logout p {
                display: inline-block;
                padding: 0.5rem;
            }
            .logout .fail {
                color: #FF0000;
            }
            .logout .success {
                color: #0d00c9;
            }

            .logout button{
                display: inline-block;
                padding: 0.5rem;;
                background-color: rgb(200, 200, 200);
            }
            .logout button:hover {
                background-color: rgb(210, 210, 210);
            }
            .logout button:focus {
                background-color: rgb(210, 210, 210);
            }
            
            /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
            /* ~~~~~~~~~~~ TABS */
            .tabs {
                margin-top: 80px;
                height: 100%;
                display: flex;
                flex-wrap: wrap;
            }
            .tabs-select {
                order: 1;
                display: flex;
                cursor: pointer;
                padding: 10px 15px;
                margin-right: 0.2rem;
                background-color: rgb(220, 220, 220);
            }
            .tabs .tab {
                order: 9;
                flex-grow: 1;
                width: 100%;
                height: 90%;
                min-width: 1050px;
                display: none;
                padding: 1rem;
                background-color: white;
            }
            .tabs input[type=checkbox] {
                accent-color: blue;
            }
            .tabs-radio {
                display: none; 
            }
            .tabs input[type="radio"]:checked + label {
                background-color: white;
            }
            .tabs input[type="radio"]:checked + label + .tab {
                display: inline-block;
            }
            .tab form {
                padding: 20px;
                border: solid rgb(230, 230, 230);
                border-radius: 10px;
                border-width: 2px;
                overflow-y: auto;
            }
            .tab form button {
                float: right;
            }
            .tab form button:hover {
                background-color: rgb(230, 230, 230);
            }
            .tab form button:focus {
                background-color: rgb(230, 230, 230);
            }
            /* ~~~~~~~~~~~ CLOCK */
            .clock-search input[type=text] {
                width: 600px;
            }
            /* ~~~~~~~~~~~ ENTRY */
            .tab.entry label  {
                display: inline-block;
                text-align: right;
                width: 28%;
                border: none;
            }
            .tab.entry input[type=text]  {
                width: 55%;
            }
            /* ~~~~~~~~~~~ REPORT */
            .tab.clock-out button {
                float: none;
            }

            /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
            /* ~~~~~~~~~~~ TABLES */
            .table-scroll {
                overflow-y: auto;
                max-height: 500px;
            }
            table {
                margin: 15px;
            }
            table thead tr {
                background-color: rgb(230, 230, 230);
                /* color: #ffffff; */
                text-align: left;
            }
            table th, table td {
                padding: 8px 15px;
            }
            table tbody tr:nth-of-type(even) {
                background-color: rgb(240, 240, 240);
            }
        </style>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                const type = document.querySelector('#id_type');
                const badge = document.querySelector('#field_badge');
                type.addEventListener('input', function () {
                    if (type.value === "1" || type.value === "2") {
                        badge.style.display = 'none';

                    } else {
                        badge.style.display = 'block';
                    }
                });
                // Trigger the input event initially if needed
                type.dispatchEvent(new Event('input'));

                // const model = document.querySelector('#model-search');
                // var select = document.querySelector("#field-search");
                // model.addEventListener('input', function () {
                //     select.innerHTML = "";
                //     if (model.value === "person") {
                //         var option = document.createElement('option');
                //         option.text = "Badge";
                //         option.value = "badge";
                //         select.add(option, 0);

                //         var option = document.createElement('option');
                //         option.text = "Full Name";
                //         option.value = "full_name";
                //         select.add(option, 0);
                //     } else {
                //         var option = document.createElement('option');
                //         option.text = "Vehicle No";
                //         option.value = "vehicle_no";
                //         select.add(option, 0);

                //         var option = document.createElement('option');
                //         option.text = "Custom Id";
                //         option.value = "custom_id";
                //         select.add(option, 0);
                //     }
                // });
                // model.dispatchEvent(new Event('input'));
            });
        </script>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/login.html
{% extends "base.html" %}

{% block content %}
<form class="login" method="POST">{% csrf_token %}  
    <h1><i>SEVA</i></h1>
    <div class="container">   
        <input type="text" placeholder="Username" name="username" required>
        <input type="password" placeholder="Password" name="password" required>  
        <button type="submit" value="login"> Login </button>
    </div>   
</form>
{% endblock content %}